server:
  port: 8071
spring:
  application:
    name: gym-crm-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          version: 1
