server:
  port: 9000
gym-crm:
  auth-server:
    issuer: http://localhost:9000
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
  datasource:
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
gym-crm:
  auth-server:
    issuer: ${OAUTH2_ISSUER_URI}