server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    consul:
      host: localhost
      port: 8500
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
  cloud:
    consul:
      host: ${CONSUL_HOST:gym-crm-consul}
      port: ${CONSUL_PORT:8500}