ALTER TABLE "user"
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE "user"
ALTER
COLUMN id
    ADD GENERATED ALWAYS AS IDENTITY;

DROP SEQUENCE IF EXISTS user_seq;

ALTER TABLE training
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE training
ALTER
COLUMN id
    ADD GENERATED ALWAYS AS IDENTITY;

DROP SEQUENCE IF EXISTS training_seq;